table Agency
	lineageTag: f9f0a749-2646-4aeb-9116-0d2b12feeee4

	column AgencyID
		dataType: int64
		formatString: 0
		lineageTag: c3b122f8-1b98-4c1b-91a5-f8ea32291284
		summarizeBy: none
		sourceColumn: AgencyID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 1face072-7dbf-4e02-b1a2-8dee08d79a98
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	partition Agency = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Kaboodle\Acumen\Sample1.xlsx"), null, true),
				    Agency_Sheet = Source{[Item="Agency",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Agency_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"AgencyID", Int64.Type}, {"Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

